name: gtspl_example
description: Demonstrates how to use the gtspl plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.2
  gtspl:
    path: ../
  path_provider: ^2.1.1
  provider: ^6.0.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/templates/
    - assets/fonts/